backend:
  name: github
  repo: Muhram07/ArsipDakwah
  branch: main

site_url: https://tangerine-dodol-29c8e4.netlify.app
display_url: https://tangerine-dodol-29c8e4.netlify.app
logo_url: https://tangerine-dodol-29c8e4.netlify.app/favicon.ico

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "artikel"
    label: "Artikel"
    folder: "data/artikel"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Isi", name: "body", widget: "markdown"}
